const images = import.meta.glob('./assets/*.{jpg,jpeg,png,webp}', { eager: true });

export const mealPlanCategories = [
  {
    category: "General Meal Plans",
    plans: [
      { 
        name: "Balanced Diet Plan", 
        image: images["./assets/bd.jpeg"]?.default || images["./assets/bd.jpeg"],
        dishes: ["Grilled Chicken & Veggies", "Brown Rice & Beans", "Greek Salad"],
        calories: 1800,
        protein: 120,
        carbs: 200,
        micronutrients: { vitaminC: "50mg", iron: "8mg", calcium: "600mg" },
        glycemicIndex: "Medium",
        alternativeMeals: ["Quinoa Bowl", "Oatmeal & Nuts"],
        preWorkoutMeal: "Banana with Peanut Butter",
        postWorkoutMeal: "Grilled Chicken with Sweet Potato",
        allergens: ["Gluten (bread)", "Nuts (optional)"],
        mealPrepTime: "30 minutes"
      },
      { 
        name: "High-Protein Plan", 
        image: images["./assets/hpd.png"]?.default || images["./assets/hpd.png"],
        dishes: ["Egg Whites & Oats", "Grilled Salmon", "Lentil Soup"],
        calories: 2200,
        protein: 180,
        carbs: 100,
        micronutrients: { vitaminB12: "5mcg", zinc: "12mg", magnesium: "400mg" },
        glycemicIndex: "Low",
        alternativeMeals: ["Turkey & Avocado Wrap", "Protein Smoothie"],
        preWorkoutMeal: "Greek Yogurt with Honey",
        postWorkoutMeal: "Tuna Salad with Brown Rice",
        allergens: ["Fish (Salmon)", "Dairy (Greek Yogurt)"],
        mealPrepTime: "40 minutes"
      },
      { 
        name: "Low-Carb Diet", 
        image: images["./assets/lcd.jpeg"]?.default || images["./assets/lcd.jpeg"],
        dishes: ["Avocado & Eggs", "Cauliflower Rice", "Zucchini Noodles"],
        calories: 1600,
        protein: 100,
        carbs: 50,
        micronutrients: { vitaminD: "600 IU", potassium: "900mg", omega3: "2g" },
        glycemicIndex: "Low",
        alternativeMeals: ["Cheese & Nuts", "Grilled Tofu Salad"],
        preWorkoutMeal: "Boiled Egg with Spinach",
        postWorkoutMeal: "Chicken & Avocado Salad",
        allergens: ["Eggs", "Dairy (Cheese)"],
        mealPrepTime: "25 minutes"
      },
      { 
        name: "High-Fiber Diet",
  image: images["./assets/hfd.png"]?.default || images["./assets/hfd.png"],
  dishes: ["Quinoa & Chickpeas", "Lentil Stew", "Mixed Berry Smoothie"],
  calories: 2000,
  protein: 90,
  carbs: 220,
  micronutrients: { fiber: "35g", vitaminC: "80mg", iron: "10mg" },
  glycemicIndex: "Medium",
  alternativeMeals: ["Oatmeal with Berries", "Sweet Potato & Black Beans"],
  preWorkoutMeal: "Banana & Almond Butter",
  postWorkoutMeal: "Lentil Soup & Whole Grain Bread",
  allergens: ["Gluten (Whole Grains)", "Legumes (Lentils, Chickpeas)"],
  mealPrepTime: "40 minutes"
      },
    ],
  },
  {
    category: "Special Dietary Plans",
    plans: [
      { 
        name: "Vegan Diet",
        image: images["./assets/vp.jpeg"]?.default || images["./assets/vp.jpeg"],
        dishes: ["Tofu Stir-fry", "Chickpea Salad", "Vegan Smoothie"],
        calories: 1900,
        protein: 80,
        carbs: 250,
        micronutrients: { vitaminB12: "0.5mcg", omega3: "1.5g", calcium: "500mg" },
        glycemicIndex: "Medium",
        alternativeMeals: ["Vegan Buddha Bowl", "Hummus & Whole Wheat Pita"],
        preWorkoutMeal: "Chia Pudding",
        postWorkoutMeal: "Lentil & Quinoa Bowl",
        allergens: ["Soy (Tofu)", "Legumes (Chickpeas)"],
        mealPrepTime: "35 minutes"
      },
      { 
        name: "Veg Diet (Indian)",
        image: images["./assets/vgi.jpeg"]?.default || images["./assets/vgi.jpeg"],
        dishes: ["Paneer Tikka", "Dal Tadka & Rice", "Vegetable Pulao"],
        calories: 2000,
        protein: 90,
        carbs: 230,
        micronutrients: { vitaminA: "900mcg", fiber: "30g", potassium: "1000mg" },
        glycemicIndex: "Medium",
        alternativeMeals: ["Roti & Sabzi", "Sprouts Chaat"],
        preWorkoutMeal: "Banana & Dates",
        postWorkoutMeal: "Curd Rice & Salad",
        allergens: ["Dairy (Paneer, Curd)"],
        mealPrepTime: "45 minutes"
      },
      { 
        name: "Gluten-Free Diet",
        image: images["./assets/gfd.jpeg"]?.default || images["./assets/gfd.jpeg"],
        dishes: ["Grilled Chicken & Quinoa", "Sweet Potato Salad", "Rice Noodles"],
        calories: 1800,
        protein: 100,
        carbs: 180,
        micronutrients: { magnesium: "350mg", zinc: "8mg", vitaminD: "600 IU" },
        glycemicIndex: "Medium",
        alternativeMeals: ["Corn Tortillas with Guacamole", "Rice Cakes & Almond Butter"],
        preWorkoutMeal: "Rice Crackers with Peanut Butter",
        postWorkoutMeal: "Quinoa & Black Bean Bowl",
        allergens: ["Nuts (Peanut Butter)", "None (Gluten-Free)"],
        mealPrepTime: "30 minutes"
      },
      { 
        name: "Keto Diet",
        image: images["./assets/kd.jpeg"]?.default || images["./assets/kd.jpeg"],
        dishes: ["Keto Omelette", "Zucchini Pasta", "Cheese & Nuts"],
        calories: 2200,
        protein: 120,
        carbs: 30,
        micronutrients: { vitaminE: "15mg", omega3: "3g", potassium: "1200mg" },
        glycemicIndex: "Low",
        alternativeMeals: ["Bacon & Avocado Bowl", "Cauliflower Mash"],
        preWorkoutMeal: "Greek Yogurt & Walnuts",
        postWorkoutMeal: "Salmon & Spinach Salad",
        allergens: ["Dairy (Cheese, Yogurt)", "Nuts"],
        mealPrepTime: "40 minutes"
      },
    ],
  },
  {
    category: "Goal-Based Plans",
    plans: [
      { 
        name: "Weight Loss Plan", 
        image: images["./assets/wlp.png"]?.default || images["./assets/wlp.png"],
        dishes: ["Grilled Fish & Greens", "Oats & Fruits", "Quinoa Salad"],
        calories: 1500,
        protein: 110,
        carbs: 130,
        micronutrients: { vitaminA: "900mcg", fiber: "30g", potassium: "1200mg" },
        glycemicIndex: "Medium",
        alternativeMeals: ["Vegetable Stir-Fry", "Chia Pudding"],
        preWorkoutMeal: "Apple with Almond Butter",
        postWorkoutMeal: "Cottage Cheese & Berries",
        allergens: ["Nuts (Almond Butter)", "Dairy (Cottage Cheese)"],
        mealPrepTime: "35 minutes"
      },
      { 
        name: "Muscle Gain Plan", 
        image: images["./assets/mgp.jpeg"]?.default || images["./assets/mgp.jpeg"],
        dishes: ["Chicken Breast & Rice", "Protein Shake", "Salmon & Sweet Potato"],
        calories: 2500,
        protein: 200,
        carbs: 250,
        micronutrients: { vitaminB6: "2mg", creatine: "5g", leucine: "8g" },
        glycemicIndex: "High",
        alternativeMeals: ["Beef & Quinoa Bowl", "Egg & Spinach Omelette"],
        preWorkoutMeal: "Oats & Whey Protein",
        postWorkoutMeal: "Grilled Steak & Roasted Veggies",
        allergens: ["Dairy (Whey)", "Eggs"],
        mealPrepTime: "45 minutes"
      },
      { 
        name: "Diabetes-Friendly",
        image: images["./assets/dfb.jpeg"]?.default || images["./assets/dfb.jpeg"],
        dishes: ["Lentil Soup", "Brown Rice & Fish", "Green Leafy Vegetables"],
        calories: 1800,
        protein: 100,
        carbs: 160,
        micronutrients: { fiber: "35g", magnesium: "400mg", vitaminC: "90mg" },
        glycemicIndex: "Low",
        alternativeMeals: ["Quinoa & Grilled Chicken", "Steamed Vegetables & Lentils"],
        preWorkoutMeal: "Greek Yogurt with Nuts",
        postWorkoutMeal: "Boiled Egg & Whole Wheat Crackers",
        allergens: ["Fish (for those allergic)", "Legumes (Lentils)"],
        mealPrepTime: "45 minutes"
      },
      { 
        name: "Heart-Healthy",
  image: images["./assets/hhp.jpeg"]?.default || images["./assets/hhp.jpeg"],
  dishes: ["Grilled Salmon", "Avocado Toast", "Oats & Nuts"],
  calories: 2000,
  protein: 90,
  carbs: 190,
  micronutrients: { omega3: "2.5g", potassium: "1300mg", vitaminE: "10mg" },
  glycemicIndex: "Low",
  alternativeMeals: ["Walnut & Berry Smoothie", "Quinoa & Roasted Veggies"],
  preWorkoutMeal: "Banana & Peanut Butter",
  postWorkoutMeal: "Salmon & Sweet Potato Mash",
  allergens: ["Fish (Salmon)", "Nuts (Almonds, Walnuts)"],
  mealPrepTime: "40 minutes"
      },
    ],
  },
];




